// <auto-generated />
// Designer file intentionally minimal — full model snapshot is in LuminaTutorsDbContextModelSnapshot.cs
// This file satisfies the EF Core partial class requirement only.
using LuminaTutors.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LuminaTutors.Infrastructure.Migrations
{
    [DbContext(typeof(LuminaTutorsDbContext))]
    [Migration("20260529000000_AddOnlineClassroomFull")]
    partial class AddOnlineClassroomFull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model is defined in LuminaTutorsDbContextModelSnapshot.cs
        }
    }
}
